apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-tareas
spec:
  replicas: 5
  selector:
    matchLabels:
      app: servicio-tareas
  template:
    metadata:
      labels:
        app: servicio-tareas
    spec:
      containers:
        - name: servicio-tareas
          image: servicio-tareas:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: /tareas, port: 8080 }
            initialDelaySeconds: 3
            periodSeconds: 3

